[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["lib = lib/forge-std/openzeppelin-contracts-master/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
